CREATE DATABASE IF NOT EXISTS loja_virtual_db;

USE loja_virtual_db;

CREATE TABLE IF NOT EXISTS categoria(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(50) NOT NULL,
descricao VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS produto(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
descricao VARCHAR(255) NOT NULL,
preco DECIMAL(10,2) NOT NULL,
estoque INT NOT NULL
);
CREATE TABLE IF NOT EXISTS paciente(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
cpf VARCHAR(15) NOT NULL,
nascimento DATE NOT NULL,
telefone VARCHAR(20) NOT NULL,
endereco VARCHAR(100) NOT NULL,
email VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS cliente(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
cpf VARCHAR(15) NOT NULL,
email VARCHAR(50) NOT NULL,
telefone VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS pedido(
id INT AUTO_INCREMENT PRIMARY KEY,
id_cliente INT NOT NULL,
data_pedido DATETIME NOT NULL,
status VARCHAR (25) NOT NULL,
valor_total VARCHAR (50) NOT NULL,
FOREIGN KEY(id_cliente) REFERENCES cliente (id)
);
CREATE TABLE IF NOT EXISTS item_pedido(
id INT AUTO_INCREMENT PRIMARY KEY,
id_pedido INT NOT NULL,
id_produto INT NOT NULL,
quantidade INT NOT NULL,
preco_unitario DECIMAL(10,2),
FOREIGN KEY (id_pedido) REFERENCES pedido (id),
FOREIGN KEY (id_produto) REFERENCES produto (id)
);
