CREATE DATABASE IF NOT EXISTS clinica_medica_db;

USE clinica_medica_db;

CREATE TABLE IF NOT EXISTS medico(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(120) NOT NULL,
crm VARCHAR(20) NOT NULL,
especialidade VARCHAR(80) NOT NULL,
telefone VARCHAR(20) NOT NULL,
email VARCHAR(120) NOT NULL
);
CREATE TABLE IF NOT EXISTS paciente(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(120) NOT NULL,
cpf VARCHAR(15) NOT NULL,
data_nascimento DATE NOT NULL,
rua VARCHAR(100) NOT NULL,
numero VARCHAR(10) NOT NULL,
cidade VARCHAR(250) NOT NULL,
cep VARCHAR(25) NOT NULL,
telefone VARCHAR(20) NOT NULL,
email VARCHAR(120) NOT NULL
);
CREATE TABLE IF NOT EXISTS convenio (
	id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    registro_ans VARCHAR(20) NOT NULL,
    telefone VARCHAR(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS agendamento(
id INT AUTO_INCREMENT PRIMARY KEY,
id_medico INT NOT NULL,
id_paciente INT NOT NULL,
data_hora DATETIME NOT NULL,
sala VARCHAR(250) NOT NULL,
valor DOUBLE NOT NULL,
observacoes TEXT NOT NULL,

FOREIGN KEY (id_medico) REFERENCES medico(id),
FOREIGN KEY (id_paciente) REFERENCES paciente(id)
);
